### ISSUE TITLE
Crash when showing notification: honeycomb + ics

### ISSUE THREAD

**Issue by caarmen** [caarmen/FRCAndroidWidget#33]
Discovered thanks to issue #32 

Steps to reproduce:
* go to the settings
* check the checkbox "System Notification"

Impacted versions: Honeycomb and Ice Cream Sandwich (apis 11-15).
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NoSuchMethodError: android.app.Notification$Builder.setLocalOnly
                      at ca.rmen.android.frccommon.compat.Api11Helper.createNotification(Api11Helper.java:45)
                      at ca.rmen.android.frccommon.compat.NotificationCompat.createNotification(NotificationCompat.java:70)
                      at ca.rmen.android.frccommon.FRCSystemNotification$ShowNotificationTask.onPostExecute(FRCSystemNotification.java:67)
                      at ca.rmen.android.frccommon.FRCSystemNotification$ShowNotificationTask.onPostExecute(FRCSystemNotification.java:37)
                      at android.os.AsyncTask.finish(AsyncTask.java:602)
```

**Comment by caarmen** [comment]
Fixed in version 1.12.3.
